// Postgres schema for the sponsorship inventory. Plain module (no "server-only")
// so it can be imported by both the runtime db layer and the migration script.
// All statements are idempotent (IF NOT EXISTS) and safe to re-run.

export const SCHEMA_STATEMENTS: string[] = [
  `CREATE TABLE IF NOT EXISTS opportunities (
      id TEXT PRIMARY KEY,
      domain TEXT NOT NULL,
      sponsorship_url TEXT NOT NULL,
      sponsor_page_url TEXT NOT NULL,
      opportunity_name TEXT,
      opportunity_type TEXT,
      city TEXT NOT NULL,
      state TEXT NOT NULL,
      local_relevance_rating TEXT,
      local_relevance_notes TEXT,
      current_sponsors_displayed TEXT,
      current_sponsors_linked TEXT,
      link_opportunity_status TEXT,
      link_evidence TEXT,
      payment_amount TEXT,
      payment_type TEXT,
      cheapest_tier_with_link TEXT,
      tier_name TEXT,
      submission_method TEXT,
      submission_url TEXT,
      contact_email TEXT,
      contact_person TEXT,
      dr DOUBLE PRECISION,
      da DOUBLE PRECISION,
      organic_traffic DOUBLE PRECISION,
      https TEXT,
      freshness_notes TEXT,
      notes TEXT,
      decision TEXT,
      human_review_trigger TEXT,
      score DOUBLE PRECISION,
      search_query_used TEXT,
      client_origin TEXT,
      run_id TEXT,
      created_at BIGINT NOT NULL,
      updated_at BIGINT NOT NULL,
      last_used_by_client TEXT,
      last_used_at BIGINT,
      UNIQUE(domain, sponsorship_url)
    )`,
  `CREATE INDEX IF NOT EXISTS idx_opportunities_city ON opportunities(city)`,
  `CREATE INDEX IF NOT EXISTS idx_opportunities_state ON opportunities(state)`,
  `CREATE INDEX IF NOT EXISTS idx_opportunities_decision ON opportunities(decision)`,
  `CREATE INDEX IF NOT EXISTS idx_opportunities_created ON opportunities(created_at)`,
  // --- Sponsorship-focused additions (idempotent ALTERs; safe to re-run, preserves existing rows) ---
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS location TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS normalized_url TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS review_reasons TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS sensitive_category TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS duplicate_of TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS last_checked_at BIGINT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS last_refreshed_at BIGINT`,
  // --- City/county/state scope tracking (single-run multi-scope research) ---
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS county TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS resolved_location_scope TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS location_confidence TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS location_evidence TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS source_query_scopes TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS technical_status TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS review_status TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS rejection_reason TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS rejection_notes TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS original_discovery_url TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS opportunity_url TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS state_abbrev TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS metro TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS location_classification TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS event_name TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS pricing_notes TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS sponsorship_tiers TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS website_link_included TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS logo_included TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS payment_method TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS event_date TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS deadline TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS assigned_client TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS submission_status TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS submission_date BIGINT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS payment_status TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS amount_paid DOUBLE PRECISION`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS expected_placement TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS expected_website_link TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS live_placement_url TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS verification_status TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS date_verified BIGINT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS link_verified TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS logo_or_business_name_verified TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS follow_up_required TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS verification_notes TEXT`,
  // Sponsorship enhancement fields (current_sponsors_linked, payment_type, contact page fallback)
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS current_sponsors_linked TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS payment_type TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS contact_page_url TEXT`,
  `ALTER TABLE opportunities ADD COLUMN IF NOT EXISTS contact_page_fallback_used TEXT`,
  `CREATE INDEX IF NOT EXISTS idx_opportunities_location ON opportunities(location)`,
  `CREATE INDEX IF NOT EXISTS idx_opportunities_domain ON opportunities(domain)`,
  `CREATE INDEX IF NOT EXISTS idx_opportunities_county ON opportunities(county)`,
  `CREATE INDEX IF NOT EXISTS idx_opportunities_resolved_scope ON opportunities(resolved_location_scope)`,
  `CREATE TABLE IF NOT EXISTS research_runs (
      id TEXT PRIMARY KEY,
      client_name TEXT NOT NULL,
      target_city TEXT NOT NULL,
      target_state TEXT NOT NULL,
      run_date BIGINT NOT NULL,
      total_candidates INTEGER,
      approved_count INTEGER,
      review_count INTEGER,
      rejected_count INTEGER,
      queries_used TEXT,
      created_at BIGINT NOT NULL
    )`,
  `CREATE INDEX IF NOT EXISTS idx_runs_client ON research_runs(client_name)`,
  `CREATE INDEX IF NOT EXISTS idx_runs_city_state ON research_runs(target_city, target_state)`,
  `CREATE INDEX IF NOT EXISTS idx_runs_created ON research_runs(created_at)`,
  // Firecrawl scrape cache: keyed by normalized URL so the same page is not
  // re-scraped within the cache window (saves free-plan credits). Failures
  // are stored too, with a short TTL, so broken URLs aren't retried in-run.
  `CREATE TABLE IF NOT EXISTS crawl_cache (
      normalized_url TEXT PRIMARY KEY,
      source_url TEXT NOT NULL,
      final_url TEXT,
      page_title TEXT,
      scraped_text TEXT,
      status TEXT NOT NULL,
      error TEXT,
      fetched_at BIGINT NOT NULL
    )`,
  `CREATE INDEX IF NOT EXISTS idx_crawl_cache_fetched ON crawl_cache(fetched_at)`,
];
